# Generated by Django 4.2.1 on 2023-05-23 02:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csr_remove_product_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='dealers')),
                ('points', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='prize_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=18)),
                ('prize', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='prizes')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
