# Generated by Django 4.2.1 on 2023-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_point_per_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
